baseURL = "http://gepulog.github.io/"
languageCode = "ja"
title = "gepulog"

theme = "hugo-thema-one"
googleAnalytics = ""

publishdir = "public"

[params]
    navigation = ["archives.md", "about.md"]

